#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Database Action Handlers Package (v11.0.0 - DEPRECATED!)

NOTE: v11.0.0 uses direct SQL execution via Qwen 2.5 Coder.
These handlers are kept for backwards compatibility but are NOT used!

SQL is generated by qwen_sql_generator.py and executed directly in chat_system.py.
"""

# Kept for backwards compatibility (not used in v11.0.0!)
try:
    from .save_handler import SaveHandler
    from .retrieve_handler import RetrieveHandler
    from .delete_handler import DeleteHandler
except ImportError:
    # Handlers may not exist - that's fine in v11.0.0
    SaveHandler = None
    RetrieveHandler = None
    DeleteHandler = None

__all__ = [
    'SaveHandler',
    'RetrieveHandler',
    'DeleteHandler'
]
